name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:      
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: "âš™ environment"
        run: |
          sudo apt-get install -y libcairo2

          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install 'standardebooks==2.6.4'

      - name: "ðŸ”Ž lint"
        id: get_errors
        run: |
          se lint . > /tmp/lint_result.txt
          ERROR_COUNT=$(grep -Ec "Error|Manual Review" /tmp/lint_result.txt) >> $GITHUB_OUTPUT
    
      - name: "ðŸš« verify lint"
        if: ${{ steps.get_errors.outputs.ERROR_COUNT > 0 }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('the publication contains errors. Check it and try again')

      - name: "âœ‚ build image"
        run: se build-images.

      - name: "ðŸ”§ build"
        run: |
          se build --kobo .
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: "ðŸš€ release" 
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          make_latest: true
          # body_path: CHANGELOG.md
          files: "*.epub"
